#!/bin/bash
#
# thomas@linuxmuster.net
# 23.01.2013
# GPL v3
#


# read paedml specific environment
. /usr/share/linuxmuster/config/dist.conf || exit 1
. $HELPERFUNCTIONS || exit 1
. $DATADIR/migration/defaults.conf || exit 1


# print command line help
usage(){
 echo
 echo "Usage: `basename $0` <options>"
 echo
 echo "Options:"
 echo
 echo " -c <config dir>  Path to config directory (optional)."
 echo "                  Default is /etc/linuxmuster/migration."
 echo " -d <target dir>  Path to target directory (must exist, mandatory)."
 echo " -h               Show this help."
 exit 1
}


# parse commandline arguments
while getopts ":c:d:h" opt; do
 case $opt in
  c) ALTCONFDIR=$OPTARG ;;
  d) TARGETDIR=$OPTARG ;;
  h) usage ;;
  \?) echo "Invalid option: -$OPTARG" >&2
      usage ;;
  :) echo "Option -$OPTARG requires an argument." >&2
     usage ;;
 esac
done


# check args
[ -z "$TARGETDIR" ] && usage
[ -d "$TARGETDIR" ] || usage
if [ -n "$ALTCONFDIR" ]; then
 [ -d "$ALTCONFDIR" ] || usage
 MIGCONFDIR="$ALTCONFDIR"
 MIGEXUSER="$MIGCONFDIR/exclude.conf"
 MIGINUSER="$MIGCONFDIR/include.conf"
fi
cd "$TARGETDIR" || usage


# delete old config file
rm -f "$MIGBACKLOG"


# print script header info
echo
echo "####" | tee -a "$MIGBACKLOG"
echo "#### Starting backup of migration data" | tee -a "$MIGBACKLOG"
echo "#### Targetdir: $TARGETDIR" | tee -a "$MIGBACKLOG"
echo "#### Configdir: $MIGCONFDIR" | tee -a "$MIGBACKLOG"
echo "#### `date`" | tee -a "$MIGBACKLOG"
echo "####" | tee -a "$MIGBACKLOG"


# concenate system and user config files
concenate_configs || error " Failed!" | tee -a "$MIGBACKLOG"


# source backup script
. "$MIGDATADIR/linuxmuster-migration-backup.sh" 2>&1 | tee -a "$MIGBACKLOG"
cp -f "$MIGBACKLOG" "$TARGETDIR"


# clean up
rm -f "$EXCONFTMP"
rm -f "$INCONFTMP"
rm -f "$INCONFILTERED"

